# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# ----------------------------------------
# Site settings
# ----------------------------------------

title: Bideo Wego
author: Bideo Wego
baseurl: /
email: bideowego@gmail.com
description: > 
  Programmatic creativity that is always developing
url: http://bideowego.com

background:
  image:
    url: https://s3.amazonaws.com/bw.bideowego/images/bideowego-banner-3.jpg

logo:
  full:
    url: https://s3.amazonaws.com/bw.bideowego/images/bw.png
  medium:
    url: /favicon-194x194.png
  thumbnail:
    url: /favicon-32x32.png

not_found:
  image:
    url: https://s3.amazonaws.com/bw.bideowego/images/404.gif
  message: One time I was looking for an internet, but I didn't finded it.


# ----------------------------------------
# Build settings
# ----------------------------------------

markdown: kramdown
kramdown:
  input: GFM
permalink: /:title


# ----------------------------------------
# Defaults
# ----------------------------------------

defaults:
  -
    scope:
        path: ''
        type: posts
    values:
      layout: post
      image:
        url: https://s3.amazonaws.com/bw.bideowego/images/bw.png
      css_id: posts-show
      comments: true




